apiVersion: appmesh.k8s.aws/v1beta1
kind: VirtualNode
metadata:
  name: flagger-loadtester
  namespace: simplerdemo
  labels:
    app: flagger-loadtester
spec:
  meshName: "corneliatest"
  listeners:
    - portMapping:
        port: 444
        protocol: http
  serviceDiscovery:
    dns:
      hostName: flagger-loadtester.simplerdemo
  backends:
    - virtualService:
        virtualServiceName: podinfo.simplerdemo
    - virtualService:
        virtualServiceName: podinfo-canary.simplerdemo
